apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  JWT_SECRET: "your-super-long-jwt-secret"
  GOOGLE_CLIENT_ID: "241945854118-ttkjts9jnco0g7jpe6fs3arht072v0mu.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  SESSION_SECRET: "your-session-secret"
